### ISSUE TITLE
Error 406 on Install

### ISSUE THREAD

**Issue by zroberts** [lcox2/AmazonAPI#6]
Guys are going to kill me, getting the same issue you had the other day in class. You ever figure out how to resolve it?

**Comment by zroberts** [comment]
I figured it out, it's because you guys have so many branhces, i added "#testing" which I believe (?) is your main branch? After that I was able to pull it down.

so
"amazonapi": "git+https://github.com/lcox2/AmazonAPI.git#testing"

fixed the 406 error for me.

**Comment by zroberts** [comment]
so 
"amazonapi": "git+https://github.com/lcox2/AmazonAPI.git#testing"

**Comment by lcox2** [comment]
That should work, if not its changed itself to amdefine on my
WishlistInterface one. Don't ask me why or how, but I am having the same
issue with Matt's, I cannot seem to find what he said to call as a
dependency

**Comment by zroberts** [comment]
"ebayfinder": "git+https://github.com/MattGable/ebayfinder.git",

thats for mats.

**Comment by lcox2** [comment]
I tried that, and it says Ebayfinder doesn't exist

Even though its sitting in my node modules folder with the --save
