### ISSUE TITLE
Couple of Issues

### ISSUE THREAD

**Issue by zroberts** [lcox2/AmazonAPI#7]
I think you guys might need to create a new node project for what we (the students outside of your group) need to use. We don't need the Wishlist application at all (the pug files, the express, the body parser, etc..), we need a hook that you guys create, to quickly dump in the predetermined information and get returned  the determined result criteria for that search (id, AID, price, etc..). I think you guys have provided us too much, and you haven't given us a way to access what we need. 

Feel free to slack me anytime tonight or Sunday if you have have any questions (zroberts) and I'm willing to help you out as time permits

**Comment by lcox2** [comment]
What issues are you having, etc.

**Comment by zroberts** [comment]
The biggest issue, is that your package that we need to work with, and your wishlist application, are all rolled into one project, instead of broken out into two projects (i think, I could just be looking at the wrong github repo).  

If you look at Mat's or mine code for our packages, there is nothing about the creating the get route, or the post route, or setting views for pug and rendering it out, or using express, or anything like that, it's just the functionality to do the search, and return back a response. 

In your Wishlist Application, you should be calling in the same Amazon Package that we are as a dependency as well. Like in my wishlist application (the part that submits the search, collects the response, and renders the pug files), I have in my package.json my dependency of ("walmart": "git+https://github.com/zroberts/walmart.git"), along with Mats and yours.  Does that make sense?

**Comment by lcox2** [comment]
I tried to clean up that repo a bit. Get rid of the junk.
